apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-one
  namespace: vs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-one
  template:
    metadata:
      labels:
        app: server-one
    spec:
      containers:
      - name: nginx
        image: aaqibshaikh199/istio-learning:CONTAINER-01
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-two
  namespace: vs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-two
  template:
    metadata:
      labels:
        app: server-two
    spec:
      containers:
      - name: nginx
        image: aaqibshaikh199/istio-learning:CONTAINER-01
        imagePullPolicy: Always
        ports:
        - containerPort: 80
